version: "3"

services:
  api:
    build: .
    entrypoint: ./entrypoint.sh
    ports:
      - "8000:8000"
    volumes:
      - .:/code
    depends_on:
      - db

  db:
    image: kartoza/postgis:12.0
    environment:
      - POSTGRES_DB=sport_match
      - POSTGRES_USER=postgres
      - POSTGRES_PASS=password
    #      - ALLOW_IP_RANGE=0.0.0.0/0
    #      # Add extensions you need to be enabled by default in the DB. Default are the three specified below
    #      - POSTGRES_MULTIPLE_EXTENSIONS=postgis,hstore,postgis_topology
    ports:
      - 25432:5432
    restart: on-failure
